### ISSUE TITLE
Error When Using with Array: `r.map is not a function`

### ISSUE THREAD

**Issue by KiddoV** [bradphelan/immer.loves.svelte#2]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
  I am encountering an issue with the `subStore `function. When trying to use `subStore `with an array, I receive the error `r.map` is not a function, indicating that the map method cannot be called on r.
  
  I was trying to update the `subStore` object to see the reflect on the root store.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

  See: https://svelte.dev/repl/0350b971798148549dcf3e955ee012dd?version=3.29.7
  Click on the button to see the re-production.
  
Not sure if I did anything wrong?

**Comment by KiddoV** [comment]
@kyy23 Can u fix it on my REPL instead, I don't want to download any file to my work PC.

**Comment by bradphelan** [comment]
Not quite sure what you are trying to do. You can't make a substore from a uni-directional transformation. If you want to create stores for individual array elements then use array store.

https://svelte.dev/repl/d49a4a2736c84ed9a54f31c612e6a8c7?version=3.29.7

**Comment by KiddoV** [comment]
Thanks! I guess I was using `subStore()` incorrectly.
